FROM nginx

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/json_log.conf /etc/nginx/json_log.conf
COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY html /usr/share/nginx/html
